#!/bin/bash

# Samples used in a small go tutorial
#
# Copyright (C) 2017,2018 framp at linux-tips-and-tricks dot de
#
# Samples for go - simple trafficlight simulation using go channels and go routines
#
# See github.com/framps/golang_tutorial for latest code

EXE=trafficlight_arm
IP=192.168.0.136
echo "Building $EXE ..."
env GOOS=linux GOARCH=arm GOARM=5 go build -o $EXE
echo "Copying $EXE to $IP ..."
scp $EXE pi@$IP:/home/pi
echo "Starting $EXE on $IP ..."
ssh pi@$IP sudo ./$EXE -leds -monitor $1
